ggDiscussionBundle:
    resource: "@ggDiscussionBundle/Controller/"
    type:     annotation
    prefix:   /

ggPartyBundle:
    resource: "@ggPartyBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern: /
    defaults: {_controller: ggSiteBundle:Site:homepage }
    requirements:
        _method: GET

ggSiteBundle:
    resource: "@ggSiteBundle/Controller/"
    type:     annotation
    prefix:   /

# Sonata cache
sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

# Sonata admin 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
