<?php

namespace gg\Bundle\PartyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends EntityRepository
{
	public function findAllOrderedByName()
    {
    	$manager = $this->getEntityManager();
        return $manager->createQuery('SELECT p FROM ggPartyBundle:Party p WHERE p.gwhen < CURRENT_DATE()')
            ->getResult();
    }
}